// <auto-generated />
namespace BaiTap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_tabe_ac : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tabe_ac));
        
        string IMigrationMetadata.Id
        {
            get { return "202110080159454_update_tabe_ac"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
